# Site settings
title: Marko Tasic's Blog
email: mtasic85@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer and researcher. Startup enthusiast. Solving hard practical problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mtasic85.github.io" # the base hostname & protocol for your site
twitter_username: mtasic85
github_username:  mtasic85

# Build settings
markdown: kramdown
